permalink: pretty
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin
sass:
  style: compressed
exclude:
  # `vendor/` is excluded because of <https://github.com/jekyll/jekyll/issues/3330>
  - vendor/
  - CNAME
  - Gemfile
  - LICENSE.md
  - README.md

strict_front_matter: true

liquid:
  error_mode: strict
  strict_filters: true


languages:
  - en
  - fr

exclude_from_localizations:
  - assets
  - media
  - _redirects

default_locale_in_subfolder: true

collections:
  redirects:
    output: true
